GET http://localhost:9005/trips

###
GET http://localhost:9005/trips?destinationLon=4.451009&destinationLat=50.849372

### /trips/{id}
### GET
GET http://localhost:9005/trips/1

###
GET http://localhost:9005/trips/0

### /trips/{id}/driver
GET http://localhost:9005/trips/12/driver

###
GET http://localhost:9005/trips/0/driver
