GET http://localhost:9005/trips?departureDate=5&?originLat=5&?originLon=5&?destinationLat=5&?destinationLon=5

###
POST http://localhost:9005/trips
Content-Type: application/json

{
  "origin": {
    "latitude": 50.849372,
    "longitude": 4.451009
  },
  "destination": {
    "latitude": 50.849372,
    "longitude": 4.451009
  },
  "departure": "2022-10-24",
  "driverId": 12,
  "availableSeating": 2
}