### Create user
POST http://localhost:9003/users
Content-Type: application/json

{
  "email": "loltest@gmail.com",
  "firstname": "stef",
  "lastname": "mir"
}

### Read user by email
GET http://localhost:9003/users?email=loltest@gmail.com

### Read user by id
GET http://localhost:9003/users/1